# -*- coding: utf-8 -*-
"""Segmentação por bordas canny.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq0DZb0liKD46zePrJMl8AwM2WdXXg5j
"""

!pip install opencv-python
import cv2
import matplotlib.pyplot as plt

def canny_edge_detection(imagem_path, limite_baixo, limite_alto):
    # Carregar a imagem
    imagem = cv2.imread(imagem_path)

    # Verificar se a imagem foi carregada corretamente
    if imagem is None:
        print(f"Erro ao carregar a imagem em: {imagem_path}")
        return

    # Converter a imagem para escala de cinza (requisito comum para Canny)
    imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

    # Aplicar o filtro de Canny
    # Os limites (thresholds) são cruciais para o resultado
    bordas_detectadas = cv2.Canny(imagem_cinza, limite_baixo, limite_alto)

    # Exibir os resultados
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(cv2.cvtColor(imagem, cv2.COLOR_BGR2RGB))
    plt.title('Imagem Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(bordas_detectadas, cmap='gray')
    plt.title('Bordas de Canny')
    plt.axis('off')

    plt.show()

# --- Exemplo de uso ---
# Substitua 'sua_imagem.jpg' pelo caminho da sua imagem
# Ajuste os limites (thresholds) conforme necessário para melhores resultados
canny_edge_detection('/content/Imagem Industrial.jpg', 100, 200)