# -*- coding: utf-8 -*-
"""Limiarização global.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPE0gD85pvlUt-KJzE2gj4zssT1hxxpK
"""

!pip install opencv-python
import cv2
import matplotlib.pyplot as plt

# Carregar a imagem em escala de cinza
# Substitua 'imagem.jpg' pelo caminho da sua imagem
imagem = cv2.imread('/content/Imagem Industrial.jpg', cv2.IMREAD_GRAYSCALE)

# Verificar se a imagem foi carregada corretamente
if imagem is None:
    print("Erro ao carregar a imagem!")
else:
    # Definir o valor do limiar (ex: 127, que é o meio do intervalo de 0 a 255)
    valor_limiar = 127
    valor_maximo = 255

    # Aplicar a limiarização binária
    # Retorna o valor do limiar usado e a imagem binarizada
    _, imagem_limiarizada = cv2.threshold(imagem, valor_limiar, valor_maximo, cv2.THRESH_BINARY)

    # Exibir as imagens (opcional)
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(imagem, cmap='gray')
    plt.title('Imagem Original (Escala de Cinza)')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(imagem_limiarizada, cmap='gray')
    plt.title(f'Imagem Limiarizada (Limiar={valor_limiar})')
    plt.axis('off')

    plt.show()